import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import axios from 'axios';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:5000';
export default function FoldersAdmin(){const router=useRouter();const [folders,setFolders]=useState([]);const [form,setForm]=useState({name:'',description:'',parentId:''});const [editing,setEditing]=useState(null);const [error,setError]=useState('');const [message,setMessage]=useState('');const headers=()=>({Authorization:`Bearer ${localStorage.getItem('token')}`});
async function load(){try{const r=await axios.get(`${API}/api/archive/admin/folders`,{headers:headers()});setFolders(r.data);}catch(e){if(e.response?.status===401||e.response?.status===403)router.push('/dashboard');else setError(e.response?.data?.error||'Ordner konnten nicht geladen werden');}}
useEffect(()=>{const token=localStorage.getItem('token');if(!token)return router.push('/login');const u=JSON.parse(localStorage.getItem('user')||'null');if(!u||!['admin','moderator'].includes(u.role))return router.push('/dashboard');load();},[router]);
const roots=useMemo(()=>folders.filter(f=>!f.parent_id),[folders]);
function startEdit(f){setEditing(f);setForm({name:f.name,description:f.description||'',parentId:f.parent_id||''});setError('');setMessage('');}
function reset(){setEditing(null);setForm({name:'',description:'',parentId:''});}
async function submit(e){e.preventDefault();setError('');setMessage('');try{const data={name:form.name,description:form.description,parentId:form.parentId||null};if(editing)await axios.patch(`${API}/api/archive/admin/folders/${editing.id}`,data,{headers:headers()});else await axios.post(`${API}/api/archive/admin/folders`,data,{headers:headers()});setMessage(editing?'Ordner aktualisiert.':'Ordner angelegt.');reset();load();}catch(e){setError(e.response?.data?.error||'Ordner konnte nicht gespeichert werden');}}
async function remove(id){if(!window.confirm('Ordner wirklich löschen? Leere Ordner können gelöscht werden.'))return;setError('');try{await axios.delete(`${API}/api/archive/admin/folders/${id}`,{headers:headers()});setMessage('Ordner gelöscht.');load();}catch(e){setError(e.response?.data?.error||'Ordner konnte nicht gelöscht werden');}}
const label=(id)=>{const f=folders.find(x=>x.id===id);return f?f.name:'Hauptordner'};
return <main className="container" style={{maxWidth:1000}}><p><Link href="/admin">← Verwaltung</Link></p><h1>Ordnerverwaltung</h1><p className="small">Ordner können verschachtelt werden. Ordner mit Beiträgen oder Unterordnern lassen sich nicht löschen.</p>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}
<section className="card"><h2>{editing?'Ordner bearbeiten':'Neuen Ordner anlegen'}</h2><form onSubmit={submit}><label>Name<input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label style={{display:'block',marginTop:12}}>Beschreibung<textarea className="textarea" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label style={{display:'block',marginTop:12}}>Übergeordneter Ordner<select className="select" value={form.parentId} onChange={e=>setForm({...form,parentId:e.target.value})}><option value="">Hauptordner</option>{folders.filter(f=>!editing||f.id!==editing.id).map(f=><option key={f.id} value={f.id}>{f.parent_id?'↳ ':''}{f.name}</option>)}</select></label><button className="button" style={{marginTop:14}} type="submit">{editing?'Speichern':'Ordner anlegen'}</button>{editing&&<button className="button secondary" type="button" style={{marginLeft:8}} onClick={reset}>Abbrechen</button>}</form></section>
<section className="card" style={{marginTop:20}}><h2>Bestehende Ordner</h2>{!folders.length&&<p className="small">Keine Ordner vorhanden.</p>}{roots.map(root=><Folder key={root.id} folder={root} folders={folders} label={label} onEdit={startEdit} onDelete={remove}/>)}</section></main>}
function Folder({folder,folders,label,onEdit,onDelete,depth=0}){const children=folders.filter(f=>f.parent_id===folder.id);return <div style={{borderTop:'1px solid #e5e7eb',padding:'14px 0',marginLeft:depth*22}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{folder.name}</strong><span className="small"> · {folder.post_count||0} Beiträge · {folder.description||'Keine Beschreibung'}</span>{folder.parent_id&&<div className="small">Unterordner von: {label(folder.parent_id)}</div>}</div><div><button className="button secondary" onClick={()=>onEdit(folder)}>Bearbeiten</button><button className="button danger" style={{marginLeft:8}} onClick={()=>onDelete(folder.id)}>Löschen</button></div></div>{children.map(c=><Folder key={c.id} folder={c} folders={folders} label={label} onEdit={onEdit} onDelete={onDelete} depth={depth+1}/>)}</div>}
