require('dotenv').config();
const express = require('express');
const cors = require('cors');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { db, seed } = require('./db');
const mediaRouter = require('./media');
const archiveRouter = require('./archive');
const userArchiveRouter = require('./userArchive');
const userAuthRouter = require('./userAuth');
const folderAdminRouter = require('./folderAdmin');
const app = express();
const PORT = process.env.PORT || 5000;
const JWT_SECRET = process.env.JWT_SECRET;
if (!JWT_SECRET || JWT_SECRET === 'development-only-secret' || JWT_SECRET === 'replace-this-with-a-long-random-secret') { if (process.env.NODE_ENV === 'production') throw new Error('JWT_SECRET muss in Produktion gesetzt werden'); console.warn('WARNUNG: Für Produktion einen langen eigenen JWT_SECRET setzen.'); }
seed();
app.use(cors({ origin: process.env.FRONTEND_ORIGIN ? process.env.FRONTEND_ORIGIN.split(',').map((x) => x.trim()) : true }));
app.use(express.json({ limit: '10mb' }));
const publicUser = (u) => ({ id: u.id, email: u.email, username: u.username, role: u.role, verified: Boolean(u.verified), createdAt: u.created_at });
const auth = (req, res, next) => { const header = req.headers.authorization; if (!header?.startsWith('Bearer ')) return res.status(401).json({ error: 'Token fehlt' }); try { req.user = jwt.verify(header.slice(7), JWT_SECRET); next(); } catch { res.status(401).json({ error: 'Token ungültig' }); } };
const role = (...roles) => (req, res, next) => roles.includes(req.user.role) ? next() : res.status(403).json({ error: 'Keine Berechtigung' });
function bootstrapAdmin() { const { ADMIN_EMAIL, ADMIN_USERNAME, ADMIN_PASSWORD } = process.env; if (!ADMIN_EMAIL || !ADMIN_USERNAME || !ADMIN_PASSWORD || ADMIN_PASSWORD.startsWith('change-this')) return; if (!db.prepare('SELECT id FROM users WHERE email=?').get(ADMIN_EMAIL)) db.prepare(`INSERT INTO users (email, username, password_hash, role, verified) VALUES (?, ?, ?, 'admin', 1)`).run(ADMIN_EMAIL.trim().toLowerCase(), ADMIN_USERNAME.trim(), bcrypt.hashSync(ADMIN_PASSWORD, 12)); }
bootstrapAdmin();
app.get('/api/health', (req, res) => res.json({ status: 'ok', database: 'sqlite' }));
app.post('/api/auth/register', async (req, res) => { const email = String(req.body.email || '').trim().toLowerCase(); const username = String(req.body.username || '').trim(); const password = String(req.body.password || ''); if (!email || !username || password.length < 8) return res.status(400).json({ error: 'Email, Username und Passwort (mindestens 8 Zeichen) erforderlich' }); try { const result = db.prepare('INSERT INTO users (email, username, password_hash) VALUES (?, ?, ?)').run(email, username, await bcrypt.hash(password, 12)); res.status(201).json({ message: 'Registrierung erfolgreich. Bitte E-Mail verifizieren und auf Admin-Freischaltung warten.', userId: result.lastInsertRowid }); } catch (e) { res.status(String(e.message).includes('UNIQUE') ? 409 : 500).json({ error: String(e.message).includes('UNIQUE') ? 'Email oder Username bereits vorhanden' : 'Registrierung fehlgeschlagen' }); } });
app.post('/api/auth/login', async (req, res) => { const user = db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email || '').trim().toLowerCase()); if (!user || !(await bcrypt.compare(req.body.password || '', user.password_hash))) return res.status(401).json({ error: 'Ungültige Zugangsdaten' }); if (!user.verified) return res.status(403).json({ error: 'E-Mail noch nicht verifiziert oder Benutzer noch nicht freigeschaltet' }); res.json({ token: jwt.sign({ id: user.id, role: user.role, username: user.username }, JWT_SECRET, { expiresIn: '7d' }), user: publicUser(user) }); });
app.get('/api/users/me', auth, (req, res) => { const u = db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id); u ? res.json(publicUser(u)) : res.status(404).json({ error: 'Benutzer nicht gefunden' }); });
app.use('/api/auth', userAuthRouter({ auth }));
app.get('/api/folders', (req, res) => res.json(db.prepare('SELECT * FROM folders ORDER BY name').all()));
app.use('/api/archive', (req, res, next) => { req.requireAuth = auth; req.requireRole = role; next(); }, archiveRouter);
app.use('/api/archive', (req, res, next) => { req.requireAuth = auth; req.requireRole = role; next(); }, userArchiveRouter);
app.use('/api/archive', (req, res, next) => { req.requireAuth = auth; req.requireRole = role; next(); }, folderAdminRouter);
app.use('/api/media', auth, mediaRouter);
app.use((err, req, res, next) => { console.error(err); res.status(500).json({ error: 'Interner Serverfehler' }); });
app.listen(PORT, () => console.log(`Backend läuft auf http://localhost:${PORT}`));
